services:
  php:
    container_name: payment-php
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - .:/app

  webserver:
    container_name: payment-nginx
    image: nginx:latest
    ports:
      - 8999:80
    volumes:
      - .:/app
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
